version: '3'
services:
  checklist-database:
    container_name: checklist-database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: checklistDatabase
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
        - "3306"
    networks:
      - checklist-network-backend

  checklist-backend:
    container_name: checklist-backend
    build: .
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - checklist-network-backend

networks:
  checklist-network-backend:
