version: '3'
services:
  checklist-database:
    container_name: checklist-database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: checklistDatabase
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - checklist-network-backend

  checklist-backend:
    container_name: checklist-backend
    build: .
    ports:
      - "8080:8080"
    depends_on:
        - checklist-database
    networks:
      - checklist-network-backend

networks:
  checklist-network-backend: