version: '3'
services:
  checklist-database:
    container_name: checklist-database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: checklistDatabase
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    healthcheck:
        test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
        timeout: 20s
        retries: 10
    networks:
      - checklist-network-backend

  checklist-backend:
    container_name: checklist-backend
    build: .
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: checklistDatabase
    ports:
      - "8080:8080"
    depends_on:
        checklist-database:
            condition: service_healthy
    networks:
      - checklist-network-backend

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-cloud.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - checklist-database
    networks:
      - checklist-network-backend

networks:
  checklist-network-backend: