server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
    include-exception: false

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: version
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/checklistDatabase
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    pattern:
      console: "%d{ISO8601} %magenta([%thread]) %highlight(%-5level) %logger : %msg%n"
      file: "%d{ISO8601} %magenta([%thread]) %highlight(%-5level) %logger : %msg%n"
    level:
      root: INFO
      org:
        springframework:
          web:
            filter:
              CommonsRequestLoggingFilter: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus